export const CART_ADD_ITEM="CART_ITEM_ADD"
export const CART_REMOVE_ITEM="CART_ITEM_REMOVE"

export const CART_SHIPPING_ADDRESS="CART_SHIPPING_ADDRESS"

export const CART_SAVE_PAYMENT_METHOD="CART_SAVE_PAYMENT_METHOD"